name: Android Pull Request & Master CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  #  test:
  #    name: Run Unit Tests
  #    runs-on: ubuntu-18.04

  #    steps:
  #      - uses: actions/checkout@v1
  #      - name: set up JDK 1.8
  #        uses: actions/setup-java@v1
  #        with:
  #          java-version: 1.8
  #      - name: Unit tests
  #        run: bash ./gradlew test --stacktrace
  lint:
    name: Run Lint
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        env:
          FIXER_IO_ACCESS_TOKEN: ${{ secrets.FIXER_IO_ACCESS_TOKEN }}
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run lint
        run: bash ./gradlew lint
#  apk:
#    name: Generate APK
#    runs-on: ubuntu-18.04
#
#    steps:
#      - uses: actions/checkout@v1
#      - name: set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#        run: bash ./gradlew assembleDebug --stacktrace
#      - name: Upload APK
#        uses: actions/upload-artifact@v1
#        with:
#          name: app
#          path: app/build/outputs/apk/debug/app-debug.apk
