name: Android Pull Request & Master CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  #  test:
  #    name: Run Unit Tests
  #    runs-on: ubuntu-18.04

  #    steps:
  #      - uses: actions/checkout@v1
  #      - name: set up JDK 1.8
  #        uses: actions/setup-java@v1
  #        with:
  #          java-version: 1.8
  #      - name: Unit tests
  #        run: bash ./gradlew test --stacktrace
  lint:
    name: Run Lint
    runs-on: ubuntu-18.04

    steps:
      #      - uses: actions/checkout@v1
      #      - name: set up JDK 1.8
      #        uses: actions/setup-java@v1
      #        with:
      #          java-version: 1.8
      #      - name: Run lint
      #        env:
      #          FIXER_IO_ACCESS_TOKEN: ${{ secrets.FIXER_IO_ACCESS_TOKEN }}
      #        run: bash ./gradlew lint

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: run Ruby
        env:
          ASDF: ${{ github.workspace }}
        run: ruby temp.rb $ASDF
#  apk:
#    name: Generate APK
#    runs-on: ubuntu-18.04
#
#    steps:
#      - uses: actions/checkout@v1
#      - name: set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#        run: bash ./gradlew assembleDebug --stacktrace
#      - name: Upload APK
#        uses: actions/upload-artifact@v1
#        with:
#          name: app
#          path: app/build/outputs/apk/debug/app-debug.apk
